/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_luwrain_windows_speech_SAPIImpl */

#ifndef _Included_org_luwrain_windows_speech_SAPIImpl
#define _Included_org_luwrain_windows_speech_SAPIImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_luwrain_windows_speech_SAPIImpl
 * Method:    getNextVoiceIdFromList
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_luwrain_windows_speech_SAPIImpl_getNextVoiceIdFromList
  (JNIEnv *, jclass);

/*
 * Class:     org_luwrain_windows_speech_SAPIImpl
 * Method:    selectCurrentVoice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_luwrain_windows_speech_SAPIImpl_selectCurrentVoice
  (JNIEnv *, jclass);

/*
 * Class:     org_luwrain_windows_speech_SAPIImpl
 * Method:    selectVoiceById
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_luwrain_windows_speech_SAPIImpl_selectVoiceById
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_luwrain_windows_speech_SAPIImpl
 * Method:    searchVoiceByAttributes
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_luwrain_windows_speech_SAPIImpl_searchVoiceByAttributes
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_luwrain_windows_speech_SAPIImpl
 * Method:    speak
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_luwrain_windows_speech_SAPIImpl_speak
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
