// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package luwrainwindows;

@net.sf.jni4net.attributes.ClrType
public class WinSpeechBackend extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected WinSpeechBackend(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public WinSpeechBackend() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        luwrainwindows.WinSpeechBackend.__ctorWinSpeechBackend0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorWinSpeechBackend0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void Say(java.lang.String text);
    
    @net.sf.jni4net.attributes.ClrMethod("(C)V")
    public native void SayLetter(char letter);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void silence();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void SetPitch(int value);
    
    public static system.Type typeof() {
        return luwrainwindows.WinSpeechBackend.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        luwrainwindows.WinSpeechBackend.staticType = staticType;
    }
    //</generated-proxy>
}
